#! /bin/bash
#
# Hook to call command on call git checkout

# To get branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Get message from relog
log=$(git reflog show $branch --pretty=oneline)

# Validate
# Is new branch
if echo "$log" | grep -q "Created from develop"; then

  # Call script
  wget -qO- https://raw.githubusercontent.com/moi-solutions/db-fork/1.1/createdb.sh | bash
fi
